// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnoPJg1-VZivI2-NXyPdIHmDsT-AOfdE',
    appId: '1:204345871873:web:04e38b788217e1c222fa00',
    messagingSenderId: '204345871873',
    projectId: 'bg4102-med-device-deign',
    authDomain: 'bg4102-med-device-deign.firebaseapp.com',
    storageBucket: 'bg4102-med-device-deign.appspot.com',
    measurementId: 'G-JY0497KC2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmFwb0e20Oc2K7JSac0tfj3pGuk7-W4k',
    appId: '1:204345871873:android:d8c5e41ebd5e0e8222fa00',
    messagingSenderId: '204345871873',
    projectId: 'bg4102-med-device-deign',
    storageBucket: 'bg4102-med-device-deign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90WE6Sv-eKIXNLKN9IMueZTP18E2siLg',
    appId: '1:204345871873:ios:ca84c991d8ba6b1822fa00',
    messagingSenderId: '204345871873',
    projectId: 'bg4102-med-device-deign',
    storageBucket: 'bg4102-med-device-deign.appspot.com',
    iosClientId: '204345871873-b96229kmtb6bg90q6vlej3dtljbv3g4d.apps.googleusercontent.com',
    iosBundleId: 'bg4102-med-device-deign.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA90WE6Sv-eKIXNLKN9IMueZTP18E2siLg',
    appId: '1:204345871873:ios:ca84c991d8ba6b1822fa00',
    messagingSenderId: '204345871873',
    projectId: 'bg4102-med-device-deign',
    storageBucket: 'bg4102-med-device-deign.appspot.com',
    iosClientId: '204345871873-b96229kmtb6bg90q6vlej3dtljbv3g4d.apps.googleusercontent.com',
    iosBundleId: 'bg4102-med-device-deign.appspot.com',
  );
}
